apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-cluster
  region: us-west-1

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 50
    labels: { role: workers }
    privateNetworking: true
    availabilityZones: ["us-west-1c", "us-west-1b"]